name: gymman
description: "Track and see nice statistics about your gym workout."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.2+1

flutter:
  uses-material-design: true